export const Position = {
    /**
     * Position of fragment within a compound word
     */
    ANY: "any",
    START: "start",
    END: "end",
    ALONE: "alone",
}


export const Type = {
    /**
     * Type of fragment; whether it can be used in forename, surname or either
     */
    ANY: "any",
    FORENAME: "forename",
    SURNAME: "surname",
}


export class Fragment {
    /**
     * Word fragment - the start or end of a forename and/or surname
     *
     * @param fragment Fragment of the word or the full word e.g. 'Octo' or 'Cheese'
     * @param position Position of the fragment within a compound word
     * @param type Type of fragment; whether it can be used in forename, surname or either
     * @param hyphenate Whether this fragment needs a hyphen before or after it
     * @param rude Whether this fragment is rude (sweary or lewd!!!)
     */

    constructor(
        fragment,
        {
            position = Position.ANY,
            type = Type.ANY,
            hyphenate = false,
            rude = false,
        },
    ) {
        this.fragment = fragment;
        this.position = position;
        this.type = type;
        this.hyphenate = hyphenate;
        this.rude = rude;
    }
}


export const fragments = [
    new Fragment(" 'core values' ", {}),
    new Fragment(" 4chan.pdf ", {}),
    new Fragment(" NaN ", {}),
    new Fragment(" Total War ", {}),
    new Fragment(" afraid of ", {}),
    new Fragment(" again!?", {position: Position.END, type: Type.SURNAME}),
    new Fragment(" against the ", {position: Position.START, type: Type.SURNAME}),
    new Fragment(" all ", {}),
    new Fragment(" and ", {position: Position.START, type: Type.SURNAME}),
    new Fragment(" around the ", {}),
    new Fragment(" artful ", {}),
    new Fragment(" basically ", {}),
    new Fragment(" be ", {}),
    new Fragment(" cop ", {}),
    new Fragment(" courage ", {}),
    new Fragment(" cowardly ", {}),
    new Fragment(" cultured ", {}),
    new Fragment(" department of ", {}),
    new Fragment(" enchanted ", {}),
    new Fragment(" enjoyer ", {}),
    new Fragment(" ensconced ", {}),
    new Fragment(" extraordinaire ", {}),
    new Fragment(" feat. ", {}),
    new Fragment(" formerly known as ", {position: Position.START, type: Type.SURNAME}),
    new Fragment(" ft. ", {}),
    new Fragment(" gates", {position: Position.END}),
    new Fragment(" go deeper ", {}),
    new Fragment(" good friend ", {}),
    new Fragment(" humanity", {position: Position.END}),
    new Fragment(" iii", {position: Position.END, type: Type.SURNAME}),
    new Fragment(" in a trenchcoat", {position: Position.END, type: Type.SURNAME}),
    new Fragment(" in sales ", {}),
    new Fragment(" infeasible ", {}),
    new Fragment(" inquisition", {position: Position.END}),
    new Fragment(" iv", {position: Position.END, type: Type.SURNAME}),
    new Fragment(" m8", {position: Position.END, type: Type.SURNAME}),
    new Fragment(" merrily ", {}),
    new Fragment(" movement", {position: Position.END}),
    new Fragment(" noscope", {position: Position.END}),
    new Fragment(" null ", {}),
    new Fragment(" o' ", {}),
    new Fragment(" of holding", {position: Position.END, type: Type.SURNAME}),
    new Fragment(" one ", {}),
    new Fragment(" our kid ", {}),
    new Fragment(" our sponsor ", {}),
    new Fragment(" pal ", {}),
    new Fragment(" pursued by ", {}),
    new Fragment(" tea party", {position: Position.END}),
    new Fragment(" technically ", {}),
    new Fragment(" the wisp ", {}),
    new Fragment(" towers", {position: Position.END}),
    new Fragment(" undefined ", {}),
    new Fragment(" upon ", {}),
    new Fragment(" without ", {position: Position.START, type: Type.SURNAME}),
    new Fragment(" x ", {}),
    new Fragment(" you! ", {}),
    new Fragment("! ", {position: Position.END}),
    new Fragment("!? ", {position: Position.END}),
    new Fragment("", {}),
    new Fragment("&block;&block;&block;&block;", {}),
    new Fragment("&trade;", {position: Position.END, type: Type.SURNAME}),
    new Fragment(", ", {position: Position.END}),
    new Fragment(", but I digress, ", {position: Position.END, type: Type.FORENAME}),
    new Fragment(", naturally", {position: Position.END, type: Type.SURNAME}),
    new Fragment("... ", {}),
    new Fragment(".exe", {position: Position.END, type: Type.SURNAME}),
    new Fragment("2", {}),
    new Fragment("2fast", {}),
    new Fragment("2furious", {}),
    new Fragment("360&deg; ", {position: Position.START}),
    new Fragment("3serious", {}),
    new Fragment("? ", {position: Position.END}),
    new Fragment("A.I. generated ", {position: Position.START}),
    new Fragment("O.G. ", {position: Position.START, type: Type.FORENAME}),
    new Fragment("ache", {}),
    new Fragment("actually ", {position: Position.START, type: Type.FORENAME}),
    new Fragment("adblock", {position: Position.ALONE}),
    new Fragment("alarm", {}),
    new Fragment("alarmist", {}),
    new Fragment("alien", {}),
    new Fragment("alpaca", {}),
    new Fragment("alpha ", {position: Position.START}),
    new Fragment("always", {}),
    new Fragment("ancient", {}),
    new Fragment("angel", {}),
    new Fragment("anger", {}),
    new Fragment("angle", {}),
    new Fragment("anti", {position: Position.START, hyphenate: true}),
    new Fragment("anus", {}),
    new Fragment("aphex ", {position: Position.START, type: Type.FORENAME}),
    new Fragment("applicable", {position: Position.ALONE}),
    new Fragment("aqua", {position: Position.START}),
    new Fragment("argue", {}),
    new Fragment("arguer", {}),
    new Fragment("armchair", {}),
    new Fragment("arse", {}),
    new Fragment("ass", {}),
    new Fragment("astute", {position: Position.ALONE}),
    new Fragment("audacious", {position: Position.ALONE}),
    new Fragment("audio", {position: Position.START}),
    new Fragment("authentically ", {position: Position.START}),
    new Fragment("avenged", {position: Position.ALONE}),
    new Fragment("b. ", {position: Position.START, type: Type.SURNAME}),
    new Fragment("baby ", {position: Position.START}),
    new Fragment("back", {}),
    new Fragment("badger", {}),
    new Fragment("badgerer", {}),
    new Fragment("badonka", {position: Position.START}),
    new Fragment("bag", {position: Position.END}),
    new Fragment("bagger", {position: Position.END}),
    new Fragment("bags", {}),
    new Fragment("baiter", {position: Position.END}),
    new Fragment("baker", {}),
    new Fragment("ball", {}),
    new Fragment("baller", {}),
    new Fragment("ballin", {position: Position.ALONE}),
    new Fragment("balls", {position: Position.END}),
    new Fragment("bambi", {}),
    new Fragment("bames", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("ban", {}),
    new Fragment("banana", {}),
    new Fragment("banned", {}),
    new Fragment("bar", {}),
    new Fragment("barber", {}),
    new Fragment("bare", {}),
    new Fragment("barge", {}),
    new Fragment("bargler", {}),
    new Fragment("bargy", {}),
    new Fragment("based", {}),
    new Fragment("baster", {}),
    new Fragment("bat", {}),
    new Fragment("batch", {position: Position.END}),
    new Fragment("batman", {position: Position.ALONE}),
    new Fragment("bean", {}),
    new Fragment("beans", {position: Position.END}),
    new Fragment("bear", {}),
    new Fragment("beard", {}),
    new Fragment("beardy", {position: Position.START}),
    new Fragment("bee", {}),
    new Fragment("beef", {}),
    new Fragment("beef", {}),
    new Fragment("beefy", {}),
    new Fragment("behind a VPN", {position: Position.ALONE, type: Type.SURNAME}),
    new Fragment("behind seven proxies", {position: Position.ALONE, type: Type.SURNAME}),
    new Fragment("behind the bike-sheds", {position: Position.ALONE, type: Type.SURNAME}),
    new Fragment("beige", {position: Position.START}),
    new Fragment("bell", {}),
    new Fragment("belly", {position: Position.END}),
    new Fragment("benedict", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("bepis", {}),
    new Fragment("berg", {position: Position.END}),
    new Fragment("bespoke", {}),
    new Fragment("bewitched", {}),
    new Fragment("bezos", {}),
    new Fragment("bichael", {}),
    new Fragment("bicycle", {}),
    new Fragment("big ", {position: Position.START}),
    new Fragment("biggus", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("bike", {}),
    new Fragment("bingus", {}),
    new Fragment("bint", {}),
    new Fragment("biscuit", {}),
    new Fragment("bite", {}),
    new Fragment("biter", {}),
    new Fragment("bitter", {}),
    new Fragment("blag", {}),
    new Fragment("blagger", {}),
    new Fragment("blam", {}),
    new Fragment("blancmange", {position: Position.ALONE}),
    new Fragment("bland", {}),
    new Fragment("blart", {}),
    new Fragment("bleating", {}),
    new Fragment("blender", {}),
    new Fragment("blob", {}),
    new Fragment("blobby", {}),
    new Fragment("blog", {}),
    new Fragment("blogs", {}),
    new Fragment("blower", {}),
    new Fragment("blue", {}),
    new Fragment("blunt", {}),
    new Fragment("blurb", {}),
    new Fragment("blurst", {}),
    new Fragment("boaty", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("body", {}),
    new Fragment("boeuf", {}),
    new Fragment("bog", {}),
    new Fragment("bogan", {}),
    new Fragment("boggle", {}),
    new Fragment("bogus", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("boi", {position: Position.ALONE}),
    new Fragment("boi", {position: Position.END}),
    new Fragment("bolt", {}),
    new Fragment("bonafide ", {position: Position.START}),
    new Fragment("bonce", {}),
    new Fragment("boner", {}),
    new Fragment("bones", {position: Position.END}),
    new Fragment("bongo", {}),
    new Fragment("bonk", {}),
    new Fragment("boob", {}),
    new Fragment("booze", {}),
    new Fragment("bore", {}),
    new Fragment("bored", {}),
    new Fragment("borg", {}),
    new Fragment("bork", {}),
    new Fragment("borks", {}),
    new Fragment("born", {}),
    new Fragment("bother", {position: Position.START}),
    new Fragment("botherer", {position: Position.END}),
    new Fragment("bowel", {}),
    new Fragment("bowler", {}),
    new Fragment("box", {}),
    new Fragment("brain", {}),
    new Fragment("bread", {}),
    new Fragment("breather", {}),
    new Fragment("breb", {}),
    new Fragment("brewer", {position: Position.END}),
    new Fragment("bro", {}),
    new Fragment("bubble", {}),
    new Fragment("bug", {}),
    new Fragment("bugger", {position: Position.END}),
    new Fragment("buggy", {}),
    new Fragment("bugs", {}),
    new Fragment("bull", {}),
    new Fragment("bully", {}),
    new Fragment("bum", {}),
    new Fragment("bumble", {}),
    new Fragment("bun", {}),
    new Fragment("bung", {position: Position.START}),
    new Fragment("bunny", {}),
    new Fragment("bunt", {}),
    new Fragment("burgler", {}),
    new Fragment("bus", {position: Position.END}),
    new Fragment("bush", {}),
    new Fragment("butt", {}),
    new Fragment("butter", {position: Position.START}),
    new Fragment("c. ", {position: Position.START, type: Type.SURNAME}),
    new Fragment("cabbage", {position: Position.START}),
    new Fragment("cake", {}),
    new Fragment("cakes", {}),
    new Fragment("calm", {}),
    new Fragment("cap", {}),
    new Fragment("capped", {}),
    new Fragment("carp", {}),
    new Fragment("carpet", {}),
    new Fragment("casual ", {position: Position.START}),
    new Fragment("cat", {}),
    new Fragment("cave", {}),
    new Fragment("caves", {}),
    new Fragment("cel", {position: Position.END}),
    new Fragment("chasm", {position: Position.END}),
    new Fragment("chauncy", {}),
    new Fragment("cheddar", {}),
    new Fragment("cheeks", {position: Position.END}),
    new Fragment("cheery", {position: Position.START}),
    new Fragment("cheese",  {}),
    new Fragment("cheese", {position: Position.END}),
    new Fragment("cheesy", {position: Position.START}),
    new Fragment("cheetoh", {}),
    new Fragment("cherry", {}),
    new Fragment("chick", {}),
    new Fragment("chicken", {}),
    new Fragment("chips", {}),
    new Fragment("chonk", {position: Position.END}),
    new Fragment("chonker", {}),
    new Fragment("chonks", {position: Position.END}),
    new Fragment("chortle", {position: Position.START}),
    new Fragment("chortler", {position: Position.END}),
    new Fragment("chu", {position: Position.END}),
    new Fragment("chub", {}),
    new Fragment("chubber", {}),
    new Fragment("chuckle", {}),
    new Fragment("chuckler", {}),
    new Fragment("chuckles", {}),
    new Fragment("chunder", {position: Position.START}),
    new Fragment("chunk", {position: Position.END}),
    new Fragment("chunks",  {position: Position.END}),
    new Fragment("chunt", {}),
    new Fragment("chutney", {}),
    new Fragment("clarence", {}),
    new Fragment("cloaca", {}),
    new Fragment("club", {}),
    new Fragment("cock", {}),
    new Fragment("code", {}),
    new Fragment("cold", {}),
    new Fragment("commode", {}),
    new Fragment("comrade ", {position: Position.START}),
    new Fragment("constable", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("constance ", {position: Position.START}),
    new Fragment("copy of ", {position: Position.START, type: Type.FORENAME}),
    new Fragment("core", {}),
    new Fragment("cork", {}),
    new Fragment("corn", {}),
    new Fragment("corner", {}),
    new Fragment("crab", {}),
    new Fragment("crack", {}),
    new Fragment("cracks", {}),
    new Fragment("crag", {}),
    new Fragment("craggy", {}),
    new Fragment("crammer", {}),
    new Fragment("crap", {}),
    new Fragment("crapper", {}),
    new Fragment("crass", {}),
    new Fragment("crazy", {}),
    new Fragment("cream", {}),
    new Fragment("creme", {}),
    new Fragment("crentist", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("crime", {}),
    new Fragment("crimes", {}),
    new Fragment("crispy", {}),
    new Fragment("croak", {}),
    new Fragment("crocs", {}),
    new Fragment("crone", {}),
    new Fragment("croney", {}),
    new Fragment("crook", {}),
    new Fragment("crotch", {}),
    new Fragment("crumpet", {}),
    new Fragment("crunchy", {}),
    new Fragment("crunder", {position: Position.START}),
    new Fragment("crust", {}),
    new Fragment("crusty", {position: Position.START}),
    new Fragment("crypto", {}),
    new Fragment("cube", {}),
    new Fragment("cucumber", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("cuddle", {}),
    new Fragment("cuddler", {}),
    new Fragment("cul-de-sac", {position: Position.ALONE, type: Type.SURNAME}),
    new Fragment("cumber", {position: Position.START}),
    new Fragment("cunning", {position: Position.START}),
    new Fragment("curried", {}),
    new Fragment("cwtch", {}),
    new Fragment("cyber", {position: Position.START}),
    new Fragment("d.j. ", {position: Position.START, type: Type.FORENAME}),
    new Fragment("daft", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("daisy", {}),
    new Fragment("dam", {}),
    new Fragment("damage", {position: Position.ALONE, type: Type.SURNAME}),
    new Fragment("damn", {}),
    new Fragment("damned", {}),
    new Fragment("danger", {}),
    new Fragment("dark", {position: Position.START}),
    new Fragment("dawg", {}),
    new Fragment("day", {}),
    new Fragment("de ", {position: Position.START, type: Type.SURNAME}),
    new Fragment("deciduous", {position: Position.ALONE}),
    new Fragment("deer", {}),
    new Fragment("deez ", {position: Position.START, type: Type.SURNAME}),
    new Fragment("demon", {}),
    new Fragment("dentist", {}),
    new Fragment("derp", {}),
    new Fragment("desert", {}),
    new Fragment("dessert", {}),
    new Fragment("dick", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("dicker", {}),
    new Fragment("dingus", {}),
    new Fragment("dink", {}),
    new Fragment("dirt", {}),
    new Fragment("disco", {}),
    new Fragment("docile", {}),
    new Fragment("docker", {}),
    new Fragment("doctor", {}),
    new Fragment("dodger", {}),
    new Fragment("dog", {}),
    new Fragment("dogger", {}),
    new Fragment("doink", {}),
    new Fragment("dolla", {}),
    new Fragment("dolt", {}),
    new Fragment("dolt", {}),
    new Fragment("dome", {}),
    new Fragment("dong", {}),
    new Fragment("dongle", {}),
    new Fragment("dongus", {}),
    new Fragment("donk", {}),
    new Fragment("donut", {}),
    new Fragment("doom", {}),
    new Fragment("doot", {}),
    new Fragment("dork", {}),
    new Fragment("dottir", {position: Position.END}),
    new Fragment("dottirdottir", {position: Position.END}),
    new Fragment("dough", {}),
    new Fragment("dragon", {}),
    new Fragment("drinker", {}),
    new Fragment("drippin", {}),
    new Fragment("driver", {position: Position.END}),
    new Fragment("drop", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("drop", {position: Position.END}),
    new Fragment("drug", {}),
    new Fragment("drugs", {}),
    new Fragment("du ", {position: Position.START, type: Type.SURNAME}),
    new Fragment("dub", {position: Position.START}),
    new Fragment("duck", {}),
    new Fragment("dumb", {}),
    new Fragment("dummy", {}),
    new Fragment("dunder", {position: Position.START}),
    new Fragment("dungeon", {position: Position.START}),
    new Fragment("dunlop", {}),
    new Fragment("dwarf", {}),
    new Fragment("dweller", {}),
    new Fragment("ear", {}),
    new Fragment("edge", {position: Position.START}),
    new Fragment("eel", {}),
    new Fragment("egg", {}),
    new Fragment("eggs", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("end", {position: Position.END}),
    new Fragment("enraged ", {position: Position.START}),
    new Fragment("exit", {}),
    new Fragment("extra", {position: Position.START}),
    new Fragment("extreme", {}),
    new Fragment("eyes", {}),
    new Fragment("f. ", {position: Position.START, type: Type.FORENAME}),
    new Fragment("face", {position: Position.END, type: Type.SURNAME}),
    new Fragment("faff", {}),
    new Fragment("falcon", {}),
    new Fragment("fam", {}),
    new Fragment("fancier", {position: Position.END}),
    new Fragment("fancy", {}),
    new Fragment("fargler", {}),
    new Fragment("farmer ", {position: Position.START}),
    new Fragment("farmer", {position: Position.END}),
    new Fragment("fart", {}),
    new Fragment("farter", {position: Position.ALONE}),
    new Fragment("fast", {}),
    new Fragment("fatboy", {position: Position.START}),
    new Fragment("fecund", {position: Position.START}),
    new Fragment("feeler", {}),
    new Fragment("feet", {}),
    new Fragment("felcher", {}),
    new Fragment("feral", {position: Position.START}),
    new Fragment("fiddle", {}),
    new Fragment("fiddler", {}),
    new Fragment("fight", {}),
    new Fragment("fine", {}),
    new Fragment("fire", {}),
    new Fragment("fishy", {}),
    new Fragment("flapper", {}),
    new Fragment("flappin", {}),
    new Fragment("flaps", {position: Position.END}),
    new Fragment("flopper", {}),
    new Fragment("floppy", {}),
    new Fragment("flower", {}),
    new Fragment("flump", {}),
    new Fragment("flumper", {}),
    new Fragment("fone", {}),
    new Fragment("foo", {}),
    new Fragment("foof", {}),
    new Fragment("foot", {}),
    new Fragment("ford", {position: Position.ALONE}),
    new Fragment("fore", {}),
    new Fragment("fortune", {}),
    new Fragment("fowl", {}),
    new Fragment("fox", {}),
    new Fragment("free", {}),
    new Fragment("frog", {}),
    new Fragment("froggy", {}),
    new Fragment("fromage", {}),
    new Fragment("fudge", {}),
    new Fragment("funk", {}),
    new Fragment("funky", {}),
    new Fragment("funny", {}),
    new Fragment("fur", {}),
    new Fragment("furry", {}),
    new Fragment("gag", {position: Position.END}),
    new Fragment("gamer", {}),
    new Fragment("gammon", {}),
    new Fragment("gangnam", {}),
    new Fragment("gangster", {position: Position.ALONE}),
    new Fragment("garden", {}),
    new Fragment("gargler", {}),
    new Fragment("garlic", {}),
    new Fragment("garms", {}),
    new Fragment("gas", {}),
    new Fragment("gash", {}),
    new Fragment("gasm", {position: Position.END}),
    new Fragment("gee", {position: Position.END}),
    new Fragment("geezer", {}),
    new Fragment("geyser", {}),
    new Fragment("ghast", {}),
    new Fragment("gherkin", {}),
    new Fragment("giggle", {}),
    new Fragment("giggler", {}),
    new Fragment("git", {}),
    new Fragment("glad", {}),
    new Fragment("gland", {}),
    new Fragment("glands", {}),
    new Fragment("glandular", {}),
    new Fragment("glasses", {}),
    new Fragment("glue", {}),
    new Fragment("gnome", {}),
    new Fragment("gobbler", {position: Position.END}),
    new Fragment("goblin", {position: Position.END}),
    new Fragment("godspeed ", {position: Position.START}),
    new Fragment("golden", {}),
    new Fragment("golfer", {}),
    new Fragment("goo", {}),
    new Fragment("goob", {}),
    new Fragment("goober", {}),
    new Fragment("gooch", {}),
    new Fragment("goon", {position: Position.END}),
    new Fragment("gooner", {position: Position.END}),
    new Fragment("goop", {}),
    new Fragment("goose", {position: Position.END}),
    new Fragment("goosey", {position: Position.START}),
    new Fragment("gorilla", {}),
    new Fragment("gorm", {}),
    new Fragment("gormen", {}),
    new Fragment("gorming", {}),
    new Fragment("grabber", {position: Position.END}),
    new Fragment("grand", {}),
    new Fragment("grape", {}),
    new Fragment("grass", {}),
    new Fragment("grease", {}),
    new Fragment("great", {position: Position.ALONE}),
    new Fragment("green", {}),
    new Fragment("greens", {}),
    new Fragment("gregg's ", {position: Position.START, type: Type.FORENAME}),
    new Fragment("greige", {}),
    new Fragment("gremlin", {}),
    new Fragment("grift", {}),
    new Fragment("grifter", {}),
    new Fragment("grime", {}),
    new Fragment("grimes", {}),
    new Fragment("gristle", {}),
    new Fragment("grower", {}),
    new Fragment("growler", {}),
    new Fragment("grunt", {}),
    new Fragment("guerilla", {}),
    new Fragment("guff", {position: Position.END}),
    new Fragment("gull", {}),
    new Fragment("gum", {}),
    new Fragment("gummer", {}),
    new Fragment("gusset", {position: Position.END}),
    new Fragment("guzzler", {position: Position.END}),
    new Fragment("hacker", {}),
    new Fragment("hag", {}),
    new Fragment("haggis", {}),
    new Fragment("haggler", {}),
    new Fragment("hags", {}),
    new Fragment("hair", {position: Position.END}),
    new Fragment("hairy", {position: Position.ALONE}),
    new Fragment("ham", {}),
    new Fragment("hanger", {position: Position.END}),
    new Fragment("hard", {}),
    new Fragment("hargler", {}),
    new Fragment("hat", {}),
    new Fragment("hatcher", {}),
    new Fragment("hater", {}),
    new Fragment("hatred", {position: Position.END}),
    new Fragment("hawk", {}),
    new Fragment("head", {position: Position.END}),
    new Fragment("head", {}),
    new Fragment("hedge", {}),
    new Fragment("heely", {position: Position.START}),
    new Fragment("heimer", {}),
    new Fragment("hell", {}),
    new Fragment("hella", {}),
    new Fragment("henge", {}),
    new Fragment("heron", {}),
    new Fragment("herring", {}),
    new Fragment("hipster", {}),
    new Fragment("hired ", {position: Position.START}),
    new Fragment("hoard", {}),
    new Fragment("hoarde", {}),
    new Fragment("hoarder", {}),
    new Fragment("hob", {}),
    new Fragment("holding", {}),
    new Fragment("hole", {position: Position.END}),
    new Fragment("holy", {}),
    new Fragment("honey", {}),
    new Fragment("honk", {position: Position.END}),
    new Fragment("honker", {}),
    new Fragment("hooner", {}),
    new Fragment("hoot", {}),
    new Fragment("hooter", {}),
    new Fragment("hope", {}),
    new Fragment("hopper", {}),
    new Fragment("horn", {position: Position.END}),
    new Fragment("horny", {}),
    new Fragment("horse", {}),
    new Fragment("hot", {}),
    new Fragment("hound", {}),
    new Fragment("house", {}),
    new Fragment("howler", {}),
    new Fragment("howling", {}),
    new Fragment("hug", {}),
    new Fragment("hugger", {}),
    new Fragment("hump", {}),
    new Fragment("humper", {}),
    new Fragment("humps", {}),
    new Fragment("husky", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("hypothetically ", {position: Position.START}),
    new Fragment("i can't believe it's not ", {position: Position.START, type: Type.FORENAME}),
    new Fragment("icey", {position: Position.START}),
    new Fragment("illegal", {}),
    new Fragment("in chat", {position: Position.ALONE, type: Type.SURNAME}),
    new Fragment("in the ", {position: Position.START, type: Type.SURNAME}),
    new Fragment("incensed", {}),
    new Fragment("ingus", {position: Position.END}),
    new Fragment("insta", {position: Position.START}),
    new Fragment("it's always ", {position: Position.START, type: Type.FORENAME}),
    new Fragment("jacker", {}),
    new Fragment("jam", {}),
    new Fragment("jelly", {}),
    new Fragment("job", {}),
    new Fragment("jobber", {}),
    new Fragment("jockey", {position: Position.END}),
    new Fragment("jog", {}),
    new Fragment("jogger", {}),
    new Fragment("jond", {position: Position.ALONE, type: Type.SURNAME}),
    new Fragment("jorts", {}),
    new Fragment("judge", {}),
    new Fragment("juggler", {position: Position.END}),
    new Fragment("jumbo", {}),
    new Fragment("jumper", {}),
    new Fragment("jungle", {}),
    new Fragment("kebab", {}),
    new Fragment("keeper", {position: Position.END}),
    new Fragment("keyboard ", {}),
    new Fragment("keygen ", {}),
    new Fragment("kid", {}),
    new Fragment("kin", {}),
    new Fragment("king", {}),
    new Fragment("knitter", {}),
    new Fragment("knob", {}),
    new Fragment("korn", {}),
    new Fragment("kun", {position: Position.END, hyphenate: true}),
    new Fragment("lad", {}),
    new Fragment("lady", {}),
    new Fragment("lard", {}),
    new Fragment("lardon", {}),
    new Fragment("lass", {}),
    new Fragment("late", {}),
    new Fragment("launderer", {}),
    new Fragment("lavender", {}),
    new Fragment("lazy", {}),
    new Fragment("leaf", {}),
    new Fragment("leafy", {}),
    new Fragment("leet", {}),
    new Fragment("legally ", {position: Position.START}),
    new Fragment("less", {}),
    new Fragment("lettuce", {}),
    new Fragment("licker", {position: Position.END}),
    new Fragment("lightning", {}),
    new Fragment("ligma ", {position: Position.START}),
    new Fragment("liker", {position: Position.END}),
    new Fragment("lingus", {position: Position.END}),
    new Fragment("lips", {position: Position.END}),
    new Fragment("lipwig", {position: Position.ALONE, type: Type.SURNAME}),
    new Fragment("lit", {}),
    new Fragment("literally ", {position: Position.START}),
    new Fragment("little ", {position: Position.START}),
    new Fragment("llama", {}),
    new Fragment("load", {}),
    new Fragment("loaf", {}),
    new Fragment("loosey", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("lord", {}),
    new Fragment("lore", {}),
    new Fragment("lorge", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("lover", {}),
    new Fragment("ludicrous", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("lump", {}),
    new Fragment("lumper", {}),
    new Fragment("lumps", {}),
    new Fragment("m.c. ", {position: Position.START, type: Type.FORENAME}),
    new Fragment("mac", {position: Position.START, type: Type.SURNAME}),
    new Fragment("machine", {}),
    new Fragment("mad", {}),
    new Fragment("mage", {}),
    new Fragment("magic", {}),
    new Fragment("major ", {position: Position.START, type: Type.FORENAME}),
    new Fragment("malfunction", {position: Position.ALONE, type: Type.SURNAME}),
    new Fragment("malice", {}),
    new Fragment("mancy", {}),
    new Fragment("mangy", {}),
    new Fragment("mare", {position: Position.END}),
    new Fragment("margarine", {position: Position.ALONE}),
    new Fragment("mash", {}),
    new Fragment("masher", {}),
    new Fragment("master", {position: Position.START}),
    new Fragment("max", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("maxxer", {position: Position.END}),
    new Fragment("mc", {position: Position.START, type: Type.SURNAME}),
    new Fragment("meat", {}),
    new Fragment("mega", {position: Position.START}),
    new Fragment("mellow", {}),
    new Fragment("meme", {position: Position.START}),
    new Fragment("menace", {}),
    new Fragment("metal", {}),
    new Fragment("micro", {position: Position.START}),
    new Fragment("mifflin", {}),
    new Fragment("miles", {}),
    new Fragment("militant ", {position: Position.START}),
    new Fragment("milk", {}),
    new Fragment("milkshake", {position: Position.ALONE}),
    new Fragment("milque", {}),
    new Fragment("mini", {position: Position.START}),
    new Fragment("missing", {}),
    new Fragment("moist", {position: Position.START}),
    new Fragment("mom's spaghetti ", {}),
    new Fragment("money", {}),
    new Fragment("monkey", {}),
    new Fragment("moo", {}),
    new Fragment("mooing", {}),
    new Fragment("more", {}),
    new Fragment("mournful", {}),
    new Fragment("mourning", {}),
    new Fragment("mouse", {}),
    new Fragment("mouth", {}),
    new Fragment("muff", {}),
    new Fragment("muffin", {}),
    new Fragment("mumble", {position: Position.START}),
    new Fragment("mumbler", {position: Position.END}),
    new Fragment("munch", {}),
    new Fragment("muncher", {}),
    new Fragment("murder", {}),
    new Fragment("musk", {}),
    new Fragment("musky", {}),
    new Fragment("my ", {position: Position.START}),
    new Fragment("mystery", {}),
    new Fragment("nargler", {}),
    new Fragment("neck", {}),
    new Fragment("nectar", {}),
    new Fragment("nerd", {}),
    new Fragment("never", {}),
    new Fragment("night", {}),
    new Fragment("no! ", {position: Position.START}),
    new Fragment("nob", {}),
    new Fragment("nobber", {}),
    new Fragment("nobody suspects ", {position: Position.START, type: Type.FORENAME}),
    new Fragment("nose", {}),
    new Fragment("not", {position: Position.START}),
    new Fragment("notorious", {position: Position.ALONE}),
    new Fragment("nouveau", {hyphenate: true}),
    new Fragment("nuisance", {}),
    new Fragment("nut", {}),
    new Fragment("nuts", {position: Position.END}),
    new Fragment("nuzzler", {position: Position.END}),
    new Fragment("oats", {}),
    new Fragment("obtuse", {position: Position.ALONE}),
    new Fragment("octo", {position: Position.START}),
    new Fragment("odorous", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("of ", {position: Position.START, type: Type.SURNAME}),
    new Fragment("ogre", {}),
    new Fragment("oh! ", {position: Position.START}),
    new Fragment("oid", {position: Position.END}),
    new Fragment("old ", {position: Position.START, type: Type.FORENAME}),
    new Fragment("omelette", {}),
    new Fragment("ominous ", {position: Position.START}),
    new Fragment("onion", {}),
    new Fragment("oops! ", {position: Position.START}),
    new Fragment("open", {position: Position.START}),
    new Fragment("oppa", {}),
    new Fragment("orangu", {position: Position.START}),
    new Fragment("organ", {}),
    new Fragment("organic ", {position: Position.START}),
    new Fragment("organs", {}),
    new Fragment("original", {position: Position.ALONE}),
    new Fragment("ornate", {}),
    new Fragment("ornery", {}),
    new Fragment("otter", {}),
    new Fragment("owl", {}),
    new Fragment("owlish", {}),
    new Fragment("owo", {}),
    new Fragment("packer", {}),
    new Fragment("pal", {}),
    new Fragment("pantry", {}),
    new Fragment("pants", {position: Position.END}),
    new Fragment("panty", {}),
    new Fragment("party", {}),
    new Fragment("pasta", {}),
    new Fragment("pasty", {}),
    new Fragment("patch", {position: Position.END}),
    new Fragment("pea", {}),
    new Fragment("peace", {}),
    new Fragment("peach", {}),
    new Fragment("peachy", {position: Position.START}),
    new Fragment("peeling", {}),
    new Fragment("peng", {}),
    new Fragment("pepper", {}),
    new Fragment("petal", {}),
    new Fragment("pharma", {}),
    new Fragment("phile", {position: Position.END}),
    new Fragment("phobe", {position: Position.END}),
    new Fragment("phone", {}),
    new Fragment("pickle", {}),
    new Fragment("pickled", {}),
    new Fragment("pickler", {}),
    new Fragment("pie", {}),
    new Fragment("pig", {position: Position.END}),
    new Fragment("pigeon", {}),
    new Fragment("pilled", {}),
    new Fragment("pilot", {}),
    new Fragment("pilsbury", {position: Position.START, type: Type.FORENAME}),
    new Fragment("pink", {}),
    new Fragment("pinky", {}),
    new Fragment("pleasant", {}),
    new Fragment("pleasing", {}),
    new Fragment("pleasure", {}),
    new Fragment("plow", {}),
    new Fragment("plower", {}),
    new Fragment("plum", {}),
    new Fragment("plump", {}),
    new Fragment("poke", {}),
    new Fragment("poker", {}),
    new Fragment("police", {}),
    new Fragment("pond", {}),
    new Fragment("poor", {}),
    new Fragment("poppy", {}),
    new Fragment("pork", {}),
    new Fragment("porker", {position: Position.END}),
    new Fragment("post", {position: Position.START, hyphenate: true}),
    new Fragment("poster", {position: Position.END}),
    new Fragment("potato", {}),
    new Fragment("potch", {}),
    new Fragment("potent", {position: Position.ALONE}),
    new Fragment("pots", {}),
    new Fragment("potter", {}),
    new Fragment("power", {}),
    new Fragment("powers", {position: Position.END}),
    new Fragment("prefect", {position: Position.ALONE}),
    new Fragment("presence", {}),
    new Fragment("pro", {position: Position.START, hyphenate: true}),
    new Fragment("proud", {}),
    new Fragment("pudding", {position: Position.START}),
    new Fragment("puddle", {}),
    new Fragment("puff", {}),
    new Fragment("punk", {}),
    new Fragment("punt", {}),
    new Fragment("punter", {}),
    new Fragment("punting", {}),
    new Fragment("purple", {}),
    new Fragment("queef", {}),
    new Fragment("queen", {}),
    new Fragment("questionable", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("quiche", {}),
    new Fragment("quids", {}),
    new Fragment("racer", {}),
    new Fragment("rad", {}),
    new Fragment("radio", {}),
    new Fragment("rag", {}),
    new Fragment("rage", {}),
    new Fragment("rancid", {}),
    new Fragment("raptor", {}),
    new Fragment("raver", {}),
    new Fragment("really ", {position: Position.START}),
    new Fragment("reddit", {}),
    new Fragment("rekt", {}),
    new Fragment("remus", {}),
    new Fragment("revenge", {}),
    new Fragment("rich", {}),
    new Fragment("ringer", {}),
    new Fragment("roadman", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("rocker", {}),
    new Fragment("rocket", {position: Position.END}),
    new Fragment("rocky", {}),
    new Fragment("romulus", {}),
    new Fragment("rough", {}),
    new Fragment("round", {}),
    new Fragment("rubber", {}),
    new Fragment("rug", {}),
    new Fragment("rumps", {}),
    new Fragment("rumpus", {}),
    new Fragment("sac", {}),
    new Fragment("sacks", {position: Position.END}),
    new Fragment("sad", {}),
    new Fragment("saint", {}),
    new Fragment("salad", {}),
    new Fragment("salmon", {}),
    new Fragment("salty", {}),
    new Fragment("san", {position: Position.END, hyphenate: true}),
    new Fragment("sand", {}),
    new Fragment("sandy", {}),
    new Fragment("sap", {}),
    new Fragment("sauce", {}),
    new Fragment("saucy", {}),
    new Fragment("saur", {position: Position.END}),
    new Fragment("saurus", {position: Position.END}),
    new Fragment("sausage", {}),
    new Fragment("savage", {}),
    new Fragment("saxo", {position: Position.START}),
    new Fragment("scare", {}),
    new Fragment("scat", {position: Position.START}),
    new Fragment("scented", {}),
    new Fragment("screw", {}),
    new Fragment("scroller", {}),
    new Fragment("scrump", {}),
    new Fragment("scrumper", {}),
    new Fragment("scrumpy", {}),
    new Fragment("scum", {}),
    new Fragment("scummer", {}),
    new Fragment("scummy", {}),
    new Fragment("sea", {}),
    new Fragment("seagull", {}),
    new Fragment("secret", {}),
    new Fragment("segway", {}),
    new Fragment("semi", {position: Position.START, hyphenate: true}),
    new Fragment("sentient ", {position: Position.ALONE}),
    new Fragment("serious", {}),
    new Fragment("services", {position: Position.END}),
    new Fragment("sevenfold", {position: Position.ALONE}),
    new Fragment("shadow", {}),
    new Fragment("shaker", {position: Position.END}),
    new Fragment("shanks", {}),
    new Fragment("shard", {}),
    new Fragment("shards", {}),
    new Fragment("shart", {}),
    new Fragment("sharter", {}),
    new Fragment("sheep", {}),
    new Fragment("shell", {}),
    new Fragment("shingled", {}),
    new Fragment("shiny", {}),
    new Fragment("shower", {}),
    new Fragment("shrek", {}),
    new Fragment("shriek", {}),
    new Fragment("shrieker", {}),
    new Fragment("shrieking", {}),
    new Fragment("shunt", {}),
    new Fragment("silly", {position: Position.START}),
    new Fragment("silver", {}),
    new Fragment("sinister ", {position: Position.START}),
    new Fragment("sitter", {}),
    new Fragment("skin", {}),
    new Fragment("slapper", {position: Position.END}),
    new Fragment("slarty", {}),
    new Fragment("slice", {position: Position.END}),
    new Fragment("slice", {}),
    new Fragment("slim", {}),
    new Fragment("slime", {}),
    new Fragment("slobber", {}),
    new Fragment("slonk", {}),
    new Fragment("slop", {}),
    new Fragment("slope", {}),
    new Fragment("slosher", {}),
    new Fragment("slow", {}),
    new Fragment("slug", {}),
    new Fragment("slugger", {}),
    new Fragment("slurp", {}),
    new Fragment("slurper", {position: Position.END}),
    new Fragment("slurry", {}),
    new Fragment("small", {position: Position.START}),
    new Fragment("smeg", {}),
    new Fragment("smeller", {position: Position.END}),
    new Fragment("smile", {}),
    new Fragment("smooth", {}),
    new Fragment("smug", {}),
    new Fragment("smuggler", {position: Position.END}),
    new Fragment("smush", {}),
    new Fragment("snail", {}),
    new Fragment("snake", {}),
    new Fragment("sneeze", {}),
    new Fragment("sniffer", {}),
    new Fragment("snitch", {}),
    new Fragment("snitcher", {}),
    new Fragment("snoot", {position: Position.END}),
    new Fragment("snooty", {position: Position.START}),
    new Fragment("snorkler", {position: Position.END}),
    new Fragment("snorter", {position: Position.END}),
    new Fragment("snot", {}),
    new Fragment("snuff", {position: Position.END}),
    new Fragment("snug", {}),
    new Fragment("soap", {}),
    new Fragment("sock", {}),
    new Fragment("soft", {}),
    new Fragment("solemn", {}),
    new Fragment("solo", {}),
    new Fragment("son", {position: Position.END}),
    new Fragment("sonic", {position: Position.START}),
    new Fragment("sonson", {position: Position.END}),
    new Fragment("sore", {}),
    new Fragment("sores", {position: Position.END}),
    new Fragment("soul", {}),
    new Fragment("soup", {}),
    new Fragment("sour", {}),
    new Fragment("spag", {}),
    new Fragment("spaghetti", {}),
    new Fragment("spam", {}),
    new Fragment("spammer", {}),
    new Fragment("spangled", {}),
    new Fragment("special", {}),
    new Fragment("specs", {}),
    new Fragment("speedy", {position: Position.START}),
    new Fragment("spelunk", {}),
    new Fragment("spelunker", {}),
    new Fragment("spelunking", {}),
    new Fragment("spender", {}),
    new Fragment("spenny", {}),
    new Fragment("sperg", {}),
    new Fragment("spice", {}),
    new Fragment("spicy", {position: Position.START}),
    new Fragment("spider", {}),
    new Fragment("spiders", {}),
    new Fragment("spit", {}),
    new Fragment("splash", {}),
    new Fragment("splasher", {}),
    new Fragment("splat", {Position: Position.END}),
    new Fragment("splats", {Position: Position.START}),
    new Fragment("spleen", {}),
    new Fragment("splurge", {}),
    new Fragment("sponge", {}),
    new Fragment("spooge", {}),
    new Fragment("spooger", {position: Position.END}),
    new Fragment("spoon", {}),
    new Fragment("sport", {}),
    new Fragment("sports", {}),
    new Fragment("spots", {}),
    new Fragment("spotted ", {position: Position.START}),
    new Fragment("spud", {}),
    new Fragment("spud", {}),
    new Fragment("square", {}),
    new Fragment("squishy", {}),
    new Fragment("stain", {}),
    new Fragment("stained", {}),
    new Fragment("stains", {}),
    new Fragment("stale", {}),
    new Fragment("stallion", {}),
    new Fragment("stan", {}),
    new Fragment("stash", {}),
    new Fragment("step", {}),
    new Fragment("stew", {}),
    new Fragment("stick", {}),
    new Fragment("stink", {}),
    new Fragment("stinker", {}),
    new Fragment("stolen", {}),
    new Fragment("stollen", {}),
    new Fragment("stonk", {}),
    new Fragment("stonker", {}),
    new Fragment("stony", {}),
    new Fragment("stooge", {}),
    new Fragment("storm", {position: Position.END}),
    new Fragment("strained", {}),
    new Fragment("strategy", {}),
    new Fragment("strawberry", {}),
    new Fragment("stroker", {}),
    new Fragment("strumpet", {}),
    new Fragment("stupid", {}),
    new Fragment("style", {}),
    new Fragment("styles", {}),
    new Fragment("succ", {}),
    new Fragment("suckle", {}),
    new Fragment("suckler", {}),
    new Fragment("summoner", {}),
    new Fragment("sunny", {position: Position.START}),
    new Fragment("swamp", {}),
    new Fragment("swan", {}),
    new Fragment("swanning", {}),
    new Fragment("sweet", {}),
    new Fragment("swindler", {position: Position.END}),
    new Fragment("synergy", {}),
    new Fragment("synyster ", {position: Position.START}),
    new Fragment("tables", {position: Position.END}),
    new Fragment("tache", {}),
    new Fragment("tackle", {}),
    new Fragment("tackler", {}),
    new Fragment("tactical", {}),
    new Fragment("tadpole", {}),
    new Fragment("taint", {}),
    new Fragment("tart", {}),
    new Fragment("tarty", {}),
    new Fragment("taste", {}),
    new Fragment("taster", {}),
    new Fragment("tasty", {}),
    new Fragment("tea", {}),
    new Fragment("tease", {}),
    new Fragment("teller", {}),
    new Fragment("temperance ", {position: Position.START}),
    new Fragment("terminally ", {position: Position.START}),
    new Fragment("terrible", {position: Position.ALONE}),
    new Fragment("the ", {position: Position.START}),
    new Fragment("thicc", {}),
    new Fragment("thief", {}),
    new Fragment("three ", {position: Position.START, type: Type.FORENAME}),
    new Fragment("throbber", {}),
    new Fragment("thunder", {position: Position.START}),
    new Fragment("tickle", {}),
    new Fragment("tickled", {}),
    new Fragment("tickler", {}),
    new Fragment("tiffin", {}),
    new Fragment("tinder", {}),
    new Fragment("tit", {position: Position.END}),
    new Fragment("toast", {}),
    new Fragment("toilet", {}),
    new Fragment("ton", {position: Position.END}),
    new Fragment("tool", {}),
    new Fragment("toot", {}),
    new Fragment("tooter", {}),
    new Fragment("tooting", {}),
    new Fragment("tosser", {}),
    new Fragment("train", {}),
    new Fragment("treat", {}),
    new Fragment("trippin", {}),
    new Fragment("trousers", {}),
    new Fragment("tumbler", {}),
    new Fragment("tumblr", {}),
    new Fragment("turd", {}),
    new Fragment("turkey", {}),
    new Fragment("turtle", {}),
    new Fragment("turtleneck", {position: Position.ALONE}),
    new Fragment("tweeter", {}),
    new Fragment("twig", {}),
    new Fragment("twiggy", {}),
    new Fragment("twigs", {}),
    new Fragment("twin", {}),
    new Fragment("undercover ", {position: Position.START}),
    new Fragment("unholy", {}),
    new Fragment("up", {position: Position.START}),
    new Fragment("ussy", {position: Position.END}),
    new Fragment("uwu", {}),
    new Fragment("various ", {position: Position.START, type: Type.FORENAME}),
    new Fragment("veloci", {position: Position.START}),
    new Fragment("vengeful", {}),
    new Fragment("vimes", {position: Position.ALONE, type: Type.SURNAME}),
    new Fragment("violet", {}),
    new Fragment("von ", {position: Position.START, type: Type.SURNAME}),
    new Fragment("waffle", {}),
    new Fragment("wag", {}),
    new Fragment("wailer", {position: Position.ALONE}),
    new Fragment("wailer", {position: Position.END}),
    new Fragment("war", {}),
    new Fragment("warlike", {}),
    new Fragment("warlock", {}),
    new Fragment("warrior", {}),
    new Fragment("wave", {}),
    new Fragment("wavey", {}),
    new Fragment("wenis", {}),
    new Fragment("wheel", {}),
    new Fragment("who art in heaven", {position: Position.ALONE, type: Type.SURNAME}),
    new Fragment("widget", {}),
    new Fragment("wild", {}),
    new Fragment("wildin", {}),
    new Fragment("willow", {}),
    new Fragment("window", {position: Position.START}),
    new Fragment("wise", {}),
    new Fragment("wisp", {}),
    new Fragment("wispy", {}),
    new Fragment("witch", {}),
    new Fragment("witchy", {position: Position.START}),
    new Fragment("wizard", {position: Position.END}),
    new Fragment("woeful", {}),
    new Fragment("wolf", {}),
    new Fragment("wombat", {}),
    new Fragment("womble", {position: Position.END}),
    new Fragment("womble", {}),
    new Fragment("wonder", {}),
    new Fragment("wood", {}),
    new Fragment("worm", {}),
    new Fragment("worms", {}),
    new Fragment("worry", {}),
    new Fragment("worst", {}),
    new Fragment("worth", {position: Position.END}),
    new Fragment("wow! ", {position: Position.START}),
    new Fragment("wrangler", {position: Position.END}),
    new Fragment("wumbo", {}),
    new Fragment("wumpus", {}),
    new Fragment("wunder", {}),
    new Fragment("wurst", {}),
    new Fragment("yawning", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("yearning", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("yeast", {}),
    new Fragment("yeasty", {}),
    new Fragment("yell", {}),
    new Fragment("yeller", {}),
    new Fragment("yelling", {}),
    new Fragment("yoghurt", {}),
]


export default fragments;
