export const Position = {
    /**
     * Position of fragment within a compound word
     */
    ANY: "any",
    START: "start",
    END: "end",
    ALONE: "alone",
}


export const Type = {
    /**
     * Type of fragment; whether it can be used in forename, surname or either
     */
    ANY: "any",
    FORENAME: "forename",
    SURNAME: "surname",
}


export class Fragment {
    /**
     * Word fragment - the start or end of a forename and/or surname
     *
     * @param fragment Fragment of the word or the full word e.g. 'Octo' or 'Cheese'
     * @param position Position of the fragment within a compound word
     * @param type Type of fragment; whether it can be used in forename, surname or either
     * @param hyphenate Whether this fragment needs a hyphen before or after it
     * @param rude Whether this fragment is rude (sweary or lewd!!!)
     */

    constructor(
        fragment,
        {
            position = Position.ANY,
            type = Type.ANY,
            hyphenate = false,
            rude = false,
        },
    ) {
        this.fragment = fragment;
        this.position = position;
        this.type = type;
        this.hyphenate = hyphenate;
        this.rude = rude;
    }
}


export const fragments = [
    new Fragment( " null ", {}),
    new Fragment( " technically ", {}),
    new Fragment( "various ", {position: Position.START, type: Type.FORENAME}),
    new Fragment(" NaN ", {}),
    new Fragment(" again!?", {position: Position.END, type: Type.SURNAME}),
    new Fragment(" against the ", {position: Position.START, type: Type.SURNAME}),
    new Fragment(" all ", {}),
    new Fragment(" and ", {position: Position.START, type: Type.SURNAME}),
    new Fragment(" artful ", {}),
    new Fragment(" cop ", {}),
    new Fragment(" enjoyer ", {}),
    new Fragment(" formerly known as ", {position: Position.START, type: Type.SURNAME}),
    new Fragment(" go deeper ", {}),
    new Fragment(" humanity", {position: Position.END}),
    new Fragment(" iii", {position: Position.END, type: Type.SURNAME}),
    new Fragment(" in a trenchcoat", {position: Position.END, type: Type.SURNAME}),
    new Fragment(" iv", {position: Position.END, type: Type.SURNAME}),
    new Fragment(" movement", {position: Position.END}),
    new Fragment(" noscope", {position: Position.END}),
    new Fragment(" our kid ", {}),
    new Fragment(" tea party", {position: Position.END}),
    new Fragment(" undefined ", {}),
    new Fragment(" without ", {position: Position.START, type: Type.SURNAME}),
    new Fragment(" you! ", {}),
    new Fragment("! ", {position: Position.END}),
    new Fragment("", {}),
    new Fragment("&trade;", {position: Position.END, type: Type.SURNAME}),
    new Fragment(", ", {position: Position.END}),
    new Fragment(", but I digress, ", {position: Position.END, type: Type.FORENAME}),
    new Fragment("... ", {}),
    new Fragment("360 ", {position: Position.START}),
    new Fragment("A.I. generated ", {position: Position.START}),
    new Fragment("O.G. ", {position: Position.START, type: Type.FORENAME}),
    new Fragment("alpha ", {position: Position.START}),
    new Fragment("anger", {}),
    new Fragment("anti", {position: Position.START, hyphenate: true}),
    new Fragment("anus", {}),
    new Fragment("aphex ", {position: Position.START, type: Type.FORENAME}),
    new Fragment("arse", {}),
    new Fragment("ass", {}),
    new Fragment("b. ", {position: Position.START, type: Type.SURNAME}),
    new Fragment("badger", {}),
    new Fragment("badonka", {position: Position.START}),
    new Fragment("bag", {position: Position.END}),
    new Fragment("baiter", {position: Position.END}),
    new Fragment("baker", {}),
    new Fragment("ball", {}),
    new Fragment("baller", {}),
    new Fragment("ballin", {position: Position.ALONE}),
    new Fragment("balls", {position: Position.END}),
    new Fragment("bames", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("based", {}),
    new Fragment("bat", {}),
    new Fragment("batch", {position: Position.END}),
    new Fragment("batman", {position: Position.ALONE}),
    new Fragment("bean", {}),
    new Fragment("beans", {position: Position.END}),
    new Fragment("bear", {}),
    new Fragment("bee", {}),
    new Fragment("beef", {}),
    new Fragment("beige", {position: Position.START}),
    new Fragment("bell", {}),
    new Fragment("belly", {position: Position.END}),
    new Fragment("benedict", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("big ", {position: Position.START}),
    new Fragment("biggus", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("blob", {}),
    new Fragment("blower", {}),
    new Fragment("boaty", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("body", {}),
    new Fragment("boeuf", {}),
    new Fragment("bog", {}),
    new Fragment("bogan", {}),
    new Fragment("bogus", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("boi", {position: Position.ALONE}),
    new Fragment("boi", {position: Position.END}),
    new Fragment("bonce", {}),
    new Fragment("boner", {}),
    new Fragment("bones", {position: Position.END}),
    new Fragment("bongo", {}),
    new Fragment("bonk", {}),
    new Fragment("boob", {}),
    new Fragment("bother", {position: Position.START}),
    new Fragment("botherer", {position: Position.END}),
    new Fragment("bowel", {}),
    new Fragment("brain", {}),
    new Fragment("brewer", {position: Position.END}),
    new Fragment("bro", {}),
    new Fragment("bubble", {}),
    new Fragment("bugger", {position: Position.END}),
    new Fragment("bum", {}),
    new Fragment("bumble", {}),
    new Fragment("bun", {}),
    new Fragment("bung", {position: Position.START}),
    new Fragment("bunny", {}),
    new Fragment("bus", {position: Position.END}),
    new Fragment("butt", {}),
    new Fragment("butter", {position: Position.START}),
    new Fragment("c. ", {position: Position.START, type: Type.SURNAME}),
    new Fragment("cabbage", {position: Position.START}),
    new Fragment("carp", {}),
    new Fragment("casual ", {position: Position.START}),
    new Fragment("cat", {}),
    new Fragment("chasm", {position: Position.END}),
    new Fragment("cheddar", {}),
    new Fragment("cheeks", {position: Position.END}),
    new Fragment("cheery", {position: Position.START}),
    new Fragment("cheese",  {}),
    new Fragment("cheese", {position: Position.END}),
    new Fragment("cheesy", {position: Position.START}),
    new Fragment("cherry", {}),
    new Fragment("chicken", {}),
    new Fragment("chips", {}),
    new Fragment("chortle", {position: Position.START}),
    new Fragment("chortler", {position: Position.END}),
    new Fragment("chub", {}),
    new Fragment("chubber", {}),
    new Fragment("chunder", {position: Position.START}),
    new Fragment("cock", {}),
    new Fragment("constable", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("constance ", {position: Position.START}),
    new Fragment("core", {}),
    new Fragment("corn", {}),
    new Fragment("crag", {}),
    new Fragment("craggy", {}),
    new Fragment("crap", {}),
    new Fragment("crapper", {}),
    new Fragment("cream", {}),
    new Fragment("crentist", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("crocs", {}),
    new Fragment("crunder", {position: Position.START}),
    new Fragment("crust", {}),
    new Fragment("crusty", {position: Position.START}),
    new Fragment("crypto", {}),
    new Fragment("cucumber", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("cul-de-sac", {position: Position.ALONE, type: Type.SURNAME}),
    new Fragment("cumber", {position: Position.START}),
    new Fragment("cunning", {position: Position.START}),
    new Fragment("cyber", {position: Position.START}),
    new Fragment("d.j. ", {position: Position.START, type: Type.FORENAME}),
    new Fragment("daft", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("damage", {position: Position.ALONE, type: Type.SURNAME}),
    new Fragment("danger", {}),
    new Fragment("dawg", {}),
    new Fragment("de ", {position: Position.START, type: Type.SURNAME}),
    new Fragment("deer", {}),
    new Fragment("deez ", {position: Position.START, type: Type.SURNAME}),
    new Fragment("demon", {}),
    new Fragment("derp", {}),
    new Fragment("dick", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("dicker", {}),
    new Fragment("dingus", {}),
    new Fragment("dink", {}),
    new Fragment("doctor", {}),
    new Fragment("dodger", {}),
    new Fragment("dog", {}),
    new Fragment("dogger", {}),
    new Fragment("doink", {}),
    new Fragment("dolla", {}),
    new Fragment("dolt", {}),
    new Fragment("dongle", {}),
    new Fragment("donk", {}),
    new Fragment("donut", {}),
    new Fragment("doot", {}),
    new Fragment("dork", {}),
    new Fragment("dough", {}),
    new Fragment("drippin", {}),
    new Fragment("driver", {position: Position.END}),
    new Fragment("drop", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("drop", {position: Position.END}),
    new Fragment("du ", {position: Position.START, type: Type.SURNAME}),
    new Fragment("dub", {position: Position.START}),
    new Fragment("duck", {}),
    new Fragment("dummy", {}),
    new Fragment("dunder", {position: Position.START}),
    new Fragment("edge", {position: Position.START}),
    new Fragment("egg", {}),
    new Fragment("eggs", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("end", {position: Position.END}),
    new Fragment("f. ", {position: Position.START, type: Type.FORENAME}),
    new Fragment("face", {position: Position.END, type: Type.SURNAME}),
    new Fragment("fart", {}),
    new Fragment("farter", {position: Position.ALONE}),
    new Fragment("fecund", {position: Position.START}),
    new Fragment("flapper", {}),
    new Fragment("flappin", {}),
    new Fragment("flaps", {position: Position.END}),
    new Fragment("flopper", {}),
    new Fragment("flower", {}),
    new Fragment("gammon", {}),
    new Fragment("gangster", {position: Position.ALONE}),
    new Fragment("gasm", {position: Position.END}),
    new Fragment("geezer", {}),
    new Fragment("geyser", {}),
    new Fragment("glue", {}),
    new Fragment("gnome", {}),
    new Fragment("gobbler", {position: Position.END}),
    new Fragment("goblin", {position: Position.END}),
    new Fragment("godspeed ", {position: Position.START}),
    new Fragment("golfer", {}),
    new Fragment("goo", {}),
    new Fragment("gooch", {}),
    new Fragment("goon", {position: Position.END}),
    new Fragment("gooner", {position: Position.END}),
    new Fragment("goop", {}),
    new Fragment("goose", {position: Position.END}),
    new Fragment("goosey", {position: Position.START}),
    new Fragment("gorilla", {}),
    new Fragment("grabber", {position: Position.END}),
    new Fragment("grease", {}),
    new Fragment("great", {position: Position.ALONE}),
    new Fragment("guff", {position: Position.END}),
    new Fragment("gusset", {position: Position.END}),
    new Fragment("guzzler", {position: Position.END}),
    new Fragment("hacker", {}),
    new Fragment("haggis", {}),
    new Fragment("ham", {}),
    new Fragment("head", {position: Position.END}),
    new Fragment("henge", {}),
    new Fragment("hole", {position: Position.END}),
    new Fragment("honk", {position: Position.END}),
    new Fragment("honker", {}),
    new Fragment("hopper", {}),
    new Fragment("horn", {position: Position.END}),
    new Fragment("horny", {}),
    new Fragment("horse", {}),
    new Fragment("hound", {}),
    new Fragment("husky", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("i can't believe it's not ", {position: Position.START, type: Type.FORENAME}),
    new Fragment("icey", {position: Position.START}),
    new Fragment("in the ", {position: Position.START, type: Type.SURNAME}),
    new Fragment("ingus", {position: Position.END}),
    new Fragment("insta", {position: Position.START}),
    new Fragment("it's always ", {position: Position.START, type: Type.FORENAME}),
    new Fragment("jelly", {}),
    new Fragment("jockey", {position: Position.END}),
    new Fragment("jond", {position: Position.ALONE, type: Type.SURNAME}),
    new Fragment("jorts", {}),
    new Fragment("juggler", {position: Position.END}),
    new Fragment("keeper", {position: Position.END}),
    new Fragment("king", {}),
    new Fragment("knob", {}),
    new Fragment("korn", {}),
    new Fragment("lad", {}),
    new Fragment("lady", {}),
    new Fragment("legally ", {position: Position.START}),
    new Fragment("licker", {position: Position.END}),
    new Fragment("ligma ", {position: Position.START}),
    new Fragment("lingus", {position: Position.END}),
    new Fragment("lips", {position: Position.END}),
    new Fragment("lipwig", {position: Position.ALONE, type: Type.SURNAME}),
    new Fragment("little ", {position: Position.START}),
    new Fragment("loaf", {}),
    new Fragment("loosey", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("lord", {}),
    new Fragment("lorge", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("ludicrous", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("m.c. ", {position: Position.START, type: Type.FORENAME}),
    new Fragment("mac", {position: Position.START, type: Type.SURNAME}),
    new Fragment("machine", {}),
    new Fragment("major ", {position: Position.START, type: Type.FORENAME}),
    new Fragment("malfunction", {position: Position.ALONE, type: Type.SURNAME}),
    new Fragment("master", {position: Position.START}),
    new Fragment("max", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("maxxer", {position: Position.END}),
    new Fragment("mc", {position: Position.START, type: Type.SURNAME}),
    new Fragment("mega", {position: Position.START}),
    new Fragment("meme", {position: Position.START}),
    new Fragment("micro", {position: Position.START}),
    new Fragment("mifflin", {}),
    new Fragment("mini", {position: Position.START}),
    new Fragment("moist", {position: Position.START}),
    new Fragment("mom's spaghetti ", {}),
    new Fragment("money", {}),
    new Fragment("mouse", {}),
    new Fragment("muff", {}),
    new Fragment("muffin", {}),
    new Fragment("mumble", {position: Position.START}),
    new Fragment("mumbler", {position: Position.END}),
    new Fragment("musk", {}),
    new Fragment("musky", {}),
    new Fragment("nerd", {}),
    new Fragment("no! ", {position: Position.START}),
    new Fragment("notorious", {position: Position.ALONE}),
    new Fragment("nuts", {position: Position.END}),
    new Fragment("nuzzler", {position: Position.END}),
    new Fragment("oats", {}),
    new Fragment("octo", {position: Position.START}),
    new Fragment("odorous", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("of ", {position: Position.START, type: Type.SURNAME}),
    new Fragment("ogre", {}),
    new Fragment("oh! ", {position: Position.START}),
    new Fragment("oops! ", {position: Position.START}),
    new Fragment("original", {position: Position.ALONE}),
    new Fragment("otter", {}),
    new Fragment("pants", {position: Position.END}),
    new Fragment("party", {}),
    new Fragment("patch", {position: Position.END}),
    new Fragment("pea", {}),
    new Fragment("peach", {}),
    new Fragment("peachy", {position: Position.START}),
    new Fragment("pig", {position: Position.END}),
    new Fragment("pilled", {}),
    new Fragment("pilsbury", {position: Position.START, type: Type.FORENAME}),
    new Fragment("pink", {}),
    new Fragment("pinky", {}),
    new Fragment("poker", {}),
    new Fragment("pork", {}),
    new Fragment("porker", {position: Position.END}),
    new Fragment("post", {position: Position.START, hyphenate: true}),
    new Fragment("potato", {}),
    new Fragment("pots", {}),
    new Fragment("power", {}),
    new Fragment("pro", {position: Position.START, hyphenate: true}),
    new Fragment("pudding", {position: Position.START}),
    new Fragment("puff", {}),
    new Fragment("punk", {}),
    new Fragment("queef", {}),
    new Fragment("queen", {}),
    new Fragment("quids", {}),
    new Fragment("racer", {}),
    new Fragment("radio", {}),
    new Fragment("rage", {}),
    new Fragment("raver", {}),
    new Fragment("rekt", {}),
    new Fragment("roadman", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("rocker", {}),
    new Fragment("rocket", {position: Position.END}),
    new Fragment("sac", {}),
    new Fragment("sacks", {position: Position.END}),
    new Fragment("saur", {position: Position.END}),
    new Fragment("saurus", {position: Position.END}),
    new Fragment("semi", {position: Position.START, hyphenate: true}),
    new Fragment("shaker", {position: Position.END}),
    new Fragment("shart", {}),
    new Fragment("sharter", {}),
    new Fragment("sheep", {}),
    new Fragment("shower", {}),
    new Fragment("shrek", {}),
    new Fragment("silly", {position: Position.START}),
    new Fragment("slapper", {position: Position.END}),
    new Fragment("slice", {position: Position.END}),
    new Fragment("slice", {}),
    new Fragment("slime", {}),
    new Fragment("slonk", {}),
    new Fragment("slop", {}),
    new Fragment("slug", {}),
    new Fragment("small", {position: Position.START}),
    new Fragment("smeg", {}),
    new Fragment("smeller", {position: Position.END}),
    new Fragment("smile", {}),
    new Fragment("smug", {}),
    new Fragment("smuggler", {position: Position.END}),
    new Fragment("snail", {}),
    new Fragment("snake", {}),
    new Fragment("sniffer", {}),
    new Fragment("snoot", {position: Position.END}),
    new Fragment("snooty", {position: Position.START}),
    new Fragment("snorkler", {position: Position.END}),
    new Fragment("snorter", {position: Position.END}),
    new Fragment("snuff", {position: Position.END}),
    new Fragment("snug", {}),
    new Fragment("sock", {}),
    new Fragment("soup", {}),
    new Fragment("spag", {}),
    new Fragment("spaghetti", {}),
    new Fragment("spangled", {}),
    new Fragment("speedy", {position: Position.START}),
    new Fragment("spicy", {position: Position.START}),
    new Fragment("splat", {Position: Position.END}),
    new Fragment("splats", {Position: Position.START}),
    new Fragment("sponge", {}),
    new Fragment("spooge", {}),
    new Fragment("spooger", {position: Position.END}),
    new Fragment("spoon", {}),
    new Fragment("spud", {}),
    new Fragment("square", {}),
    new Fragment("step", {}),
    new Fragment("stonk", {}),
    new Fragment("stonker", {}),
    new Fragment("stooge", {}),
    new Fragment("storm", {position: Position.END}),
    new Fragment("stroker", {}),
    new Fragment("succ", {}),
    new Fragment("sunny", {position: Position.START}),
    new Fragment("swamp", {}),
    new Fragment("swindler", {position: Position.END}),
    new Fragment("tables", {position: Position.END}),
    new Fragment("taint", {}),
    new Fragment("tart", {}),
    new Fragment("temperance ", {position: Position.START}),
    new Fragment("terrible", {position: Position.ALONE}),
    new Fragment("the ", {position: Position.START}),
    new Fragment("thicc", {}),
    new Fragment("three ", {position: Position.START, type: Type.FORENAME}),
    new Fragment("thunder", {position: Position.START}),
    new Fragment("tinder", {}),
    new Fragment("tit", {position: Position.END}),
    new Fragment("train", {}),
    new Fragment("trippin", {}),
    new Fragment("undercover ", {position: Position.START}),
    new Fragment("up", {position: Position.START}),
    new Fragment("ussy", {position: Position.END}),
    new Fragment("vimes", {position: Position.ALONE, type: Type.SURNAME}),
    new Fragment("von ", {position: Position.START, type: Type.SURNAME}),
    new Fragment("waffle", {}),
    new Fragment("wailer", {position: Position.ALONE}),
    new Fragment("wailer", {position: Position.END}),
    new Fragment("wenis", {}),
    new Fragment("widget", {}),
    new Fragment("window", {position: Position.START}),
    new Fragment("wizard", {position: Position.END}),
    new Fragment("womble", {position: Position.END}),
    new Fragment("womble", {}),
    new Fragment("wood", {}),
    new Fragment("worry", {}),
    new Fragment("worth", {position: Position.END}),
    new Fragment("wow! ", {position: Position.START}),
    new Fragment("wrangler", {position: Position.END}),
]


export default fragments;
