export const Position = {
    /**
     * Position of fragment within a compound word
     */
    ANY: "any",
    START: "start",
    END: "end",
    ALONE: "alone",
}


export const Type = {
    /**
     * Type of fragment; whether it can be used in forename, surname or either
     */
    ANY: "any",
    FORENAME: "forename",
    SURNAME: "surname",
}


export class Fragment {
    /**
     * Word fragment - the start or end of a forename and/or surname
     *
     * @param fragment Fragment of the word or the full word e.g. 'Octo' or 'Cheese'
     * @param position Position of the fragment within a compound word
     * @param type Type of fragment; whether it can be used in forename, surname or either
     * @param hyphenate Whether this fragment needs a hyphen before or after it
     * @param rude Whether this fragment is rude (sweary or lewd!!!)
     */

    constructor(
        fragment,
        {
            position = Position.ANY,
            type = Type.ANY,
            hyphenate = false,
            rude = false,
        },
    ) {
        this.fragment = fragment;
        this.position = position;
        this.type = type;
        this.hyphenate = hyphenate;
        this.rude = rude;
    }
}


export const fragments = [
    new Fragment(" 'core values' ", {}),
    new Fragment(" 4chan.pdf ", {}),
    new Fragment(" NaN ", {}),
    new Fragment(" afraid of ", {}),
    new Fragment(" again!?", {position: Position.END, type: Type.SURNAME}),
    new Fragment(" against the ", {position: Position.START, type: Type.SURNAME}),
    new Fragment(" all ", {}),
    new Fragment(" and ", {position: Position.START, type: Type.SURNAME}),
    new Fragment(" artful ", {}),
    new Fragment(" basically ", {}),
    new Fragment(" cop ", {}),
    new Fragment(" courage ", {}),
    new Fragment(" cowardly ", {}),
    new Fragment(" enjoyer ", {}),
    new Fragment(" formerly known as ", {position: Position.START, type: Type.SURNAME}),
    new Fragment(" gates", {position: Position.END}),
    new Fragment(" go deeper ", {}),
    new Fragment(" humanity", {position: Position.END}),
    new Fragment(" iii", {position: Position.END, type: Type.SURNAME}),
    new Fragment(" in a trenchcoat", {position: Position.END, type: Type.SURNAME}),
    new Fragment(" in sales ", {}),
    new Fragment(" iv", {position: Position.END, type: Type.SURNAME}),
    new Fragment(" movement", {position: Position.END}),
    new Fragment(" noscope", {position: Position.END}),
    new Fragment(" null ", {}),
    new Fragment(" our kid ", {}),
    new Fragment(" our sponsor ", {}),
    new Fragment(" tea party", {position: Position.END}),
    new Fragment(" technically ", {}),
    new Fragment(" towers", {position: Position.END}),
    new Fragment(" undefined ", {}),
    new Fragment(" without ", {position: Position.START, type: Type.SURNAME}),
    new Fragment(" you! ", {}),
    new Fragment(".exe", {position: Position.END, type: Type.SURNAME}),
    new Fragment("! ", {position: Position.END}),
    new Fragment("!? ", {position: Position.END}),
    new Fragment("", {}),
    new Fragment("&block;&block;&block;&block;", {}),
    new Fragment("&trade;", {position: Position.END, type: Type.SURNAME}),
    new Fragment(", ", {position: Position.END}),
    new Fragment(", but I digress, ", {position: Position.END, type: Type.FORENAME}),
    new Fragment(", naturally", {position: Position.END, type: Type.SURNAME}),
    new Fragment("... ", {}),
    new Fragment("360&deg; ", {position: Position.START}),
    new Fragment("? ", {position: Position.END}),
    new Fragment("A.I. generated ", {position: Position.START}),
    new Fragment("O.G. ", {position: Position.START, type: Type.FORENAME}),
    new Fragment("actually ", {position: Position.START, type: Type.FORENAME}),
    new Fragment("adblock", {position: Position.ALONE}),
    new Fragment("alpha ", {position: Position.START}),
    new Fragment("anger", {}),
    new Fragment("anti", {position: Position.START, hyphenate: true}),
    new Fragment("anus", {}),
    new Fragment("aphex ", {position: Position.START, type: Type.FORENAME}),
    new Fragment("applicable", {position: Position.ALONE}),
    new Fragment("arse", {}),
    new Fragment("ass", {}),
    new Fragment("audio", {position: Position.START}),
    new Fragment("avenged", {position: Position.ALONE}),
    new Fragment("b. ", {position: Position.START, type: Type.SURNAME}),
    new Fragment("baby ", {position: Position.START}),
    new Fragment("badger", {}),
    new Fragment("badonka", {position: Position.START}),
    new Fragment("bag", {position: Position.END}),
    new Fragment("bagger", {position: Position.END}),
    new Fragment("baiter", {position: Position.END}),
    new Fragment("baker", {}),
    new Fragment("ball", {}),
    new Fragment("baller", {}),
    new Fragment("ballin", {position: Position.ALONE}),
    new Fragment("balls", {position: Position.END}),
    new Fragment("bames", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("based", {}),
    new Fragment("bat", {}),
    new Fragment("batch", {position: Position.END}),
    new Fragment("batman", {position: Position.ALONE}),
    new Fragment("bean", {}),
    new Fragment("beans", {position: Position.END}),
    new Fragment("bear", {}),
    new Fragment("beard", {}),
    new Fragment("beardy", {position: Position.START}),
    new Fragment("bee", {}),
    new Fragment("beef", {}),
    new Fragment("behind a VPN", {position: Position.ALONE, type: Type.SURNAME}),
    new Fragment("behind seven proxies", {position: Position.ALONE, type: Type.SURNAME}),
    new Fragment("behind the bike-sheds", {position: Position.ALONE, type: Type.SURNAME}),
    new Fragment("beige", {position: Position.START}),
    new Fragment("bell", {}),
    new Fragment("belly", {position: Position.END}),
    new Fragment("benedict", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("bepis", {}),
    new Fragment("berg", {position: Position.END}),
    new Fragment("bezos", {}),
    new Fragment("big ", {position: Position.START}),
    new Fragment("biggus", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("bingus", {}),
    new Fragment("biscuit", {}),
    new Fragment("blob", {}),
    new Fragment("blobby", {}),
    new Fragment("blower", {}),
    new Fragment("blue", {}),
    new Fragment("boaty", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("body", {}),
    new Fragment("boeuf", {}),
    new Fragment("bog", {}),
    new Fragment("bogan", {}),
    new Fragment("boggle", {}),
    new Fragment("bogus", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("boi", {position: Position.ALONE}),
    new Fragment("boi", {position: Position.END}),
    new Fragment("bonafide ", {position: Position.START}),
    new Fragment("bonce", {}),
    new Fragment("boner", {}),
    new Fragment("bones", {position: Position.END}),
    new Fragment("bongo", {}),
    new Fragment("bonk", {}),
    new Fragment("boob", {}),
    new Fragment("borg", {}),
    new Fragment("born", {}),
    new Fragment("bother", {position: Position.START}),
    new Fragment("botherer", {position: Position.END}),
    new Fragment("bowel", {}),
    new Fragment("bowler", {}),
    new Fragment("brain", {}),
    new Fragment("brewer", {position: Position.END}),
    new Fragment("bro", {}),
    new Fragment("bubble", {}),
    new Fragment("bugger", {position: Position.END}),
    new Fragment("bum", {}),
    new Fragment("bumble", {}),
    new Fragment("bun", {}),
    new Fragment("bung", {position: Position.START}),
    new Fragment("bunny", {}),
    new Fragment("bus", {position: Position.END}),
    new Fragment("bush", {}),
    new Fragment("butt", {}),
    new Fragment("butter", {position: Position.START}),
    new Fragment("c. ", {position: Position.START, type: Type.SURNAME}),
    new Fragment("cabbage", {position: Position.START}),
    new Fragment("carp", {}),
    new Fragment("carpet", {}),
    new Fragment("casual ", {position: Position.START}),
    new Fragment("cat", {}),
    new Fragment("cel", {position: Position.END}),
    new Fragment("chasm", {position: Position.END}),
    new Fragment("cheddar", {}),
    new Fragment("cheeks", {position: Position.END}),
    new Fragment("cheery", {position: Position.START}),
    new Fragment("cheese",  {}),
    new Fragment("cheese", {position: Position.END}),
    new Fragment("cheesy", {position: Position.START}),
    new Fragment("cherry", {}),
    new Fragment("chicken", {}),
    new Fragment("chips", {}),
    new Fragment("chonk", {position: Position.END}),
    new Fragment("chonker", {}),
    new Fragment("chonks", {position: Position.END}),
    new Fragment("chortle", {position: Position.START}),
    new Fragment("chortler", {position: Position.END}),
    new Fragment("chu", {position: Position.END}),
    new Fragment("chub", {}),
    new Fragment("chubber", {}),
    new Fragment("chunder", {position: Position.START}),
    new Fragment("chunk", {position: Position.END}),
    new Fragment("chunks",  {position: Position.END}),
    new Fragment("chunt", {}),
    new Fragment("cloaca", {}),
    new Fragment("cock", {}),
    new Fragment("commode", {}),
    new Fragment("comrade ", {position: Position.START}),
    new Fragment("constable", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("constance ", {position: Position.START}),
    new Fragment("copy of ", {position: Position.START, type: Type.FORENAME}),
    new Fragment("core", {}),
    new Fragment("corn", {}),
    new Fragment("crag", {}),
    new Fragment("craggy", {}),
    new Fragment("crap", {}),
    new Fragment("crapper", {}),
    new Fragment("cream", {}),
    new Fragment("crentist", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("crocs", {}),
    new Fragment("crook", {}),
    new Fragment("crotch", {}),
    new Fragment("crunder", {position: Position.START}),
    new Fragment("crust", {}),
    new Fragment("crusty", {position: Position.START}),
    new Fragment("crypto", {}),
    new Fragment("cucumber", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("cul-de-sac", {position: Position.ALONE, type: Type.SURNAME}),
    new Fragment("cumber", {position: Position.START}),
    new Fragment("cunning", {position: Position.START}),
    new Fragment("cwtch", {}),
    new Fragment("cyber", {position: Position.START}),
    new Fragment("d.j. ", {position: Position.START, type: Type.FORENAME}),
    new Fragment("daft", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("damage", {position: Position.ALONE, type: Type.SURNAME}),
    new Fragment("danger", {}),
    new Fragment("dark", {position: Position.START}),
    new Fragment("dawg", {}),
    new Fragment("day", {}),
    new Fragment("de ", {position: Position.START, type: Type.SURNAME}),
    new Fragment("deer", {}),
    new Fragment("deez ", {position: Position.START, type: Type.SURNAME}),
    new Fragment("demon", {}),
    new Fragment("derp", {}),
    new Fragment("dick", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("dicker", {}),
    new Fragment("dingus", {}),
    new Fragment("dink", {}),
    new Fragment("dirt", {}),
    new Fragment("disco", {}),
    new Fragment("docker", {}),
    new Fragment("doctor", {}),
    new Fragment("dodger", {}),
    new Fragment("dog", {}),
    new Fragment("dogger", {}),
    new Fragment("doink", {}),
    new Fragment("dolla", {}),
    new Fragment("dolt", {}),
    new Fragment("dong", {}),
    new Fragment("dongle", {}),
    new Fragment("donk", {}),
    new Fragment("donut", {}),
    new Fragment("doom", {}),
    new Fragment("doot", {}),
    new Fragment("dork", {}),
    new Fragment("dottir", {position: Position.END}),
    new Fragment("dottirdottir", {position: Position.END}),
    new Fragment("dough", {}),
    new Fragment("dragon", {}),
    new Fragment("drippin", {}),
    new Fragment("driver", {position: Position.END}),
    new Fragment("drop", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("drop", {position: Position.END}),
    new Fragment("du ", {position: Position.START, type: Type.SURNAME}),
    new Fragment("dub", {position: Position.START}),
    new Fragment("duck", {}),
    new Fragment("dumb", {}),
    new Fragment("dummy", {}),
    new Fragment("dunder", {position: Position.START}),
    new Fragment("dungeon", {position: Position.START}),
    new Fragment("dwarf", {}),
    new Fragment("edge", {position: Position.START}),
    new Fragment("egg", {}),
    new Fragment("eggs", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("end", {position: Position.END}),
    new Fragment("extra", {position: Position.START}),
    new Fragment("f. ", {position: Position.START, type: Type.FORENAME}),
    new Fragment("face", {position: Position.END, type: Type.SURNAME}),
    new Fragment("falcon", {}),
    new Fragment("fancier", {position: Position.END}),
    new Fragment("fancy", {}),
    new Fragment("farmer ", {position: Position.START}),
    new Fragment("farmer", {position: Position.END}),
    new Fragment("fart", {}),
    new Fragment("farter", {position: Position.ALONE}),
    new Fragment("fatboy", {position: Position.START}),
    new Fragment("fecund", {position: Position.START}),
    new Fragment("feral", {position: Position.START}),
    new Fragment("fight", {}),
    new Fragment("fine", {}),
    new Fragment("fire", {}),
    new Fragment("flapper", {}),
    new Fragment("flappin", {}),
    new Fragment("flaps", {position: Position.END}),
    new Fragment("flopper", {}),
    new Fragment("floppy", {}),
    new Fragment("flower", {}),
    new Fragment("fone", {}),
    new Fragment("foo", {}),
    new Fragment("foot", {}),
    new Fragment("ford", {position: Position.ALONE}),
    new Fragment("fortune", {}),
    new Fragment("fromage", {}),
    new Fragment("fudge", {}),
    new Fragment("funk", {}),
    new Fragment("funky", {}),
    new Fragment("fur", {}),
    new Fragment("furry", {}),
    new Fragment("gammon", {}),
    new Fragment("gangster", {position: Position.ALONE}),
    new Fragment("garden", {}),
    new Fragment("garlic", {}),
    new Fragment("gag", {position: Position.END}),
    new Fragment("gas", {}),
    new Fragment("gasm", {position: Position.END}),
    new Fragment("geezer", {}),
    new Fragment("geyser", {}),
    new Fragment("git", {}),
    new Fragment("glad", {}),
    new Fragment("glue", {}),
    new Fragment("gnome", {}),
    new Fragment("gobbler", {position: Position.END}),
    new Fragment("goblin", {position: Position.END}),
    new Fragment("godspeed ", {position: Position.START}),
    new Fragment("golden", {}),
    new Fragment("golfer", {}),
    new Fragment("goo", {}),
    new Fragment("gooch", {}),
    new Fragment("goon", {position: Position.END}),
    new Fragment("gooner", {position: Position.END}),
    new Fragment("goop", {}),
    new Fragment("goose", {position: Position.END}),
    new Fragment("goosey", {position: Position.START}),
    new Fragment("gorilla", {}),
    new Fragment("grabber", {position: Position.END}),
    new Fragment("grass", {}),
    new Fragment("grease", {}),
    new Fragment("great", {position: Position.ALONE}),
    new Fragment("gregg's ", {position: Position.START, type: Type.FORENAME}),
    new Fragment("greige", {}),
    new Fragment("gremlin", {}),
    new Fragment("gristle", {}),
    new Fragment("grunt", {}),
    new Fragment("guff", {position: Position.END}),
    new Fragment("gusset", {position: Position.END}),
    new Fragment("guzzler", {position: Position.END}),
    new Fragment("hacker", {}),
    new Fragment("haggis", {}),
    new Fragment("hair", {position: Position.END}),
    new Fragment("hairy", {position: Position.ALONE}),
    new Fragment("ham", {}),
    new Fragment("hanger", {position: Position.END}),
    new Fragment("hard", {}),
    new Fragment("hater", {}),
    new Fragment("hatred", {position: Position.END}),
    new Fragment("hawk", {}),
    new Fragment("head", {position: Position.END}),
    new Fragment("head", {}),
    new Fragment("hedge", {}),
    new Fragment("heely", {position: Position.START}),
    new Fragment("henge", {}),
    new Fragment("herring", {}),
    new Fragment("hipster", {}),
    new Fragment("hole", {position: Position.END}),
    new Fragment("honk", {position: Position.END}),
    new Fragment("honker", {}),
    new Fragment("hoot", {}),
    new Fragment("hooter", {}),
    new Fragment("hopper", {}),
    new Fragment("horn", {position: Position.END}),
    new Fragment("horny", {}),
    new Fragment("horse", {}),
    new Fragment("hound", {}),
    new Fragment("house", {}),
    new Fragment("hug", {}),
    new Fragment("hugger", {}),
    new Fragment("husky", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("i can't believe it's not ", {position: Position.START, type: Type.FORENAME}),
    new Fragment("icey", {position: Position.START}),
    new Fragment("in chat", {position: Position.ALONE, type: Type.SURNAME}),
    new Fragment("in the ", {position: Position.START, type: Type.SURNAME}),
    new Fragment("ingus", {position: Position.END}),
    new Fragment("insta", {position: Position.START}),
    new Fragment("it's always ", {position: Position.START, type: Type.FORENAME}),
    new Fragment("jacker", {}),
    new Fragment("jam", {}),
    new Fragment("jelly", {}),
    new Fragment("jockey", {position: Position.END}),
    new Fragment("jond", {position: Position.ALONE, type: Type.SURNAME}),
    new Fragment("jorts", {}),
    new Fragment("juggler", {position: Position.END}),
    new Fragment("jumper", {}),
    new Fragment("kebab", {}),
    new Fragment("keeper", {position: Position.END}),
    new Fragment("keygen ", {}),
    new Fragment("keyboard ", {}),
    new Fragment("king", {}),
    new Fragment("knob", {}),
    new Fragment("korn", {}),
    new Fragment("lad", {}),
    new Fragment("lady", {}),
    new Fragment("lavender", {}),
    new Fragment("legally ", {position: Position.START}),
    new Fragment("licker", {position: Position.END}),
    new Fragment("ligma ", {position: Position.START}),
    new Fragment("liker", {position: Position.END}),
    new Fragment("lingus", {position: Position.END}),
    new Fragment("lips", {position: Position.END}),
    new Fragment("lipwig", {position: Position.ALONE, type: Type.SURNAME}),
    new Fragment("literally ", {position: Position.START}),
    new Fragment("little ", {position: Position.START}),
    new Fragment("loaf", {}),
    new Fragment("loosey", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("lord", {}),
    new Fragment("lorge", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("lover", {}),
    new Fragment("ludicrous", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("m.c. ", {position: Position.START, type: Type.FORENAME}),
    new Fragment("mac", {position: Position.START, type: Type.SURNAME}),
    new Fragment("machine", {}),
    new Fragment("mad", {}),
    new Fragment("major ", {position: Position.START, type: Type.FORENAME}),
    new Fragment("malfunction", {position: Position.ALONE, type: Type.SURNAME}),
    new Fragment("malice", {}),
    new Fragment("master", {position: Position.START}),
    new Fragment("max", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("maxxer", {position: Position.END}),
    new Fragment("mc", {position: Position.START, type: Type.SURNAME}),
    new Fragment("mega", {position: Position.START}),
    new Fragment("meme", {position: Position.START}),
    new Fragment("micro", {position: Position.START}),
    new Fragment("mifflin", {}),
    new Fragment("miles", {}),
    new Fragment("militant ", {position: Position.START}),
    new Fragment("mini", {position: Position.START}),
    new Fragment("moist", {position: Position.START}),
    new Fragment("mom's spaghetti ", {}),
    new Fragment("money", {}),
    new Fragment("monkey", {}),
    new Fragment("mouse", {}),
    new Fragment("muff", {}),
    new Fragment("muffin", {}),
    new Fragment("mumble", {position: Position.START}),
    new Fragment("mumbler", {position: Position.END}),
    new Fragment("musk", {}),
    new Fragment("musky", {}),
    new Fragment("nerd", {}),
    new Fragment("night", {}),
    new Fragment("no! ", {position: Position.START}),
    new Fragment("not", {position: Position.START}),
    new Fragment("notorious", {position: Position.ALONE}),
    new Fragment("nuisance", {}),
    new Fragment("nut", {}),
    new Fragment("nuts", {position: Position.END}),
    new Fragment("nuzzler", {position: Position.END}),
    new Fragment("oats", {}),
    new Fragment("obtuse", {position: Position.ALONE}),
    new Fragment("octo", {position: Position.START}),
    new Fragment("odorous", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("of ", {position: Position.START, type: Type.SURNAME}),
    new Fragment("ogre", {}),
    new Fragment("oh! ", {position: Position.START}),
    new Fragment("oid", {position: Position.END}),
    new Fragment("old ", {position: Position.START, type: Type.FORENAME}),
    new Fragment("omelette", {}),
    new Fragment("onion", {}),
    new Fragment("oops! ", {position: Position.START}),
    new Fragment("open", {position: Position.START}),
    new Fragment("orangu", {position: Position.START}),
    new Fragment("organic ", {position: Position.START}),
    new Fragment("original", {position: Position.ALONE}),
    new Fragment("otter", {}),
    new Fragment("owl", {}),
    new Fragment("owo", {}),
    new Fragment("packer", {}),
    new Fragment("pants", {position: Position.END}),
    new Fragment("party", {}),
    new Fragment("pasty", {}),
    new Fragment("patch", {position: Position.END}),
    new Fragment("pea", {}),
    new Fragment("peach", {}),
    new Fragment("peachy", {position: Position.START}),
    new Fragment("pepper", {}),
    new Fragment("phile", {position: Position.END}),
    new Fragment("phobe", {position: Position.END}),
    new Fragment("phone", {}),
    new Fragment("pie", {}),
    new Fragment("pig", {position: Position.END}),
    new Fragment("pilled", {}),
    new Fragment("pilsbury", {position: Position.START, type: Type.FORENAME}),
    new Fragment("pink", {}),
    new Fragment("pinky", {}),
    new Fragment("poker", {}),
    new Fragment("pork", {}),
    new Fragment("porker", {position: Position.END}),
    new Fragment("post", {position: Position.START, hyphenate: true}),
    new Fragment("poster", {position: Position.END}),
    new Fragment("potato", {}),
    new Fragment("potent", {position: Position.ALONE}),
    new Fragment("pots", {}),
    new Fragment("power", {}),
    new Fragment("powers", {position: Position.END}),
    new Fragment("prefect", {position: Position.ALONE}),
    new Fragment("pro", {position: Position.START, hyphenate: true}),
    new Fragment("proud", {}),
    new Fragment("pudding", {position: Position.START}),
    new Fragment("puff", {}),
    new Fragment("punk", {}),
    new Fragment("queef", {}),
    new Fragment("queen", {}),
    new Fragment("questionable", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("quiche", {}),
    new Fragment("quids", {}),
    new Fragment("racer", {}),
    new Fragment("rad", {}),
    new Fragment("radio", {}),
    new Fragment("rag", {}),
    new Fragment("rage", {}),
    new Fragment("raver", {}),
    new Fragment("really ", {position: Position.START}),
    new Fragment("reddit", {}),
    new Fragment("rekt", {}),
    new Fragment("roadman", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("rocker", {}),
    new Fragment("rocket", {position: Position.END}),
    new Fragment("rubber", {}),
    new Fragment("sac", {}),
    new Fragment("sacks", {position: Position.END}),
    new Fragment("sad", {}),
    new Fragment("salad", {}),
    new Fragment("salmon", {}),
    new Fragment("saur", {position: Position.END}),
    new Fragment("saurus", {position: Position.END}),
    new Fragment("sausage", {}),
    new Fragment("savage", {}),
    new Fragment("saxo", {position: Position.START}),
    new Fragment("scat", {position: Position.START}),
    new Fragment("screw", {}),
    new Fragment("scroller", {}),
    new Fragment("segway", {}),
    new Fragment("semi", {position: Position.START, hyphenate: true}),
    new Fragment("services", {position: Position.END}),
    new Fragment("sevenfold", {position: Position.ALONE}),
    new Fragment("shadow", {}),
    new Fragment("shaker", {position: Position.END}),
    new Fragment("shanks", {}),
    new Fragment("shart", {}),
    new Fragment("sharter", {}),
    new Fragment("sheep", {}),
    new Fragment("shower", {}),
    new Fragment("shrek", {}),
    new Fragment("silly", {position: Position.START}),
    new Fragment("silver", {}),
    new Fragment("sinister ", {position: Position.START}),
    new Fragment("slapper", {position: Position.END}),
    new Fragment("slice", {position: Position.END}),
    new Fragment("slice", {}),
    new Fragment("slim", {}),
    new Fragment("slime", {}),
    new Fragment("slobber", {}),
    new Fragment("slonk", {}),
    new Fragment("slop", {}),
    new Fragment("slug", {}),
    new Fragment("slurp", {}),
    new Fragment("slurper", {position: Position.END}),
    new Fragment("small", {position: Position.START}),
    new Fragment("smeg", {}),
    new Fragment("smeller", {position: Position.END}),
    new Fragment("smile", {}),
    new Fragment("smug", {}),
    new Fragment("smuggler", {position: Position.END}),
    new Fragment("smush", {}),
    new Fragment("snail", {}),
    new Fragment("snake", {}),
    new Fragment("sniffer", {}),
    new Fragment("snitch", {}),
    new Fragment("snitcher", {}),
    new Fragment("snoot", {position: Position.END}),
    new Fragment("snooty", {position: Position.START}),
    new Fragment("snorkler", {position: Position.END}),
    new Fragment("snorter", {position: Position.END}),
    new Fragment("snot", {}),
    new Fragment("snuff", {position: Position.END}),
    new Fragment("snug", {}),
    new Fragment("sock", {}),
    new Fragment("soft", {}),
    new Fragment("son", {position: Position.END}),
    new Fragment("sonic", {position: Position.START}),
    new Fragment("sonson", {position: Position.END}),
    new Fragment("sores", {position: Position.END}),
    new Fragment("soup", {}),
    new Fragment("spag", {}),
    new Fragment("spaghetti", {}),
    new Fragment("spangled", {}),
    new Fragment("speedy", {position: Position.START}),
    new Fragment("sperg", {}),
    new Fragment("spicy", {position: Position.START}),
    new Fragment("splat", {Position: Position.END}),
    new Fragment("splats", {Position: Position.START}),
    new Fragment("splurge", {}),
    new Fragment("sponge", {}),
    new Fragment("spooge", {}),
    new Fragment("spooger", {position: Position.END}),
    new Fragment("spoon", {}),
    new Fragment("spots", {}),
    new Fragment("spotted ", {position: Position.START}),
    new Fragment("spud", {}),
    new Fragment("square", {}),
    new Fragment("squishy", {}),
    new Fragment("stash", {}),
    new Fragment("step", {}),
    new Fragment("stick", {}),
    new Fragment("stonk", {}),
    new Fragment("stonker", {}),
    new Fragment("stooge", {}),
    new Fragment("storm", {position: Position.END}),
    new Fragment("strawberry", {}),
    new Fragment("stroker", {}),
    new Fragment("stupid", {}),
    new Fragment("succ", {}),
    new Fragment("sunny", {position: Position.START}),
    new Fragment("swamp", {}),
    new Fragment("swindler", {position: Position.END}),
    new Fragment("synergy", {}),
    new Fragment("synyster ", {position: Position.START}),
    new Fragment("tables", {position: Position.END}),
    new Fragment("tache", {}),
    new Fragment("taint", {}),
    new Fragment("tart", {}),
    new Fragment("teller", {}),
    new Fragment("temperance ", {position: Position.START}),
    new Fragment("terminally ", {position: Position.START}),
    new Fragment("terrible", {position: Position.ALONE}),
    new Fragment("the ", {position: Position.START}),
    new Fragment("thicc", {}),
    new Fragment("thief", {}),
    new Fragment("three ", {position: Position.START, type: Type.FORENAME}),
    new Fragment("throbber", {}),
    new Fragment("thunder", {position: Position.START}),
    new Fragment("tinder", {}),
    new Fragment("tit", {position: Position.END}),
    new Fragment("toilet", {}),
    new Fragment("tool", {}),
    new Fragment("tosser", {}),
    new Fragment("train", {}),
    new Fragment("trippin", {}),
    new Fragment("trousers", {}),
    new Fragment("undercover ", {position: Position.START}),
    new Fragment("up", {position: Position.START}),
    new Fragment("ussy", {position: Position.END}),
    new Fragment("uwu", {}),
    new Fragment("various ", {position: Position.START, type: Type.FORENAME}),
    new Fragment("vimes", {position: Position.ALONE, type: Type.SURNAME}),
    new Fragment("von ", {position: Position.START, type: Type.SURNAME}),
    new Fragment("waffle", {}),
    new Fragment("wailer", {position: Position.ALONE}),
    new Fragment("wailer", {position: Position.END}),
    new Fragment("war", {}),
    new Fragment("warrior", {}),
    new Fragment("wave", {}),
    new Fragment("wenis", {}),
    new Fragment("wheel", {}),
    new Fragment("who art in heaven", {position: Position.ALONE, type: Type.SURNAME}),
    new Fragment("widget", {}),
    new Fragment("window", {position: Position.START}),
    new Fragment("witch", {}),
    new Fragment("witchy", {position: Position.START}),
    new Fragment("wizard", {position: Position.END}),
    new Fragment("wolf", {}),
    new Fragment("womble", {position: Position.END}),
    new Fragment("womble", {}),
    new Fragment("wood", {}),
    new Fragment("worry", {}),
    new Fragment("worst", {}),
    new Fragment("worth", {position: Position.END}),
    new Fragment("worm", {}),
    new Fragment("wow! ", {position: Position.START}),
    new Fragment("wrangler", {position: Position.END}),
    new Fragment("wurst", {}),
    new Fragment("yawning", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("yearning", {position: Position.ALONE, type: Type.FORENAME}),
]


export default fragments;
